[package]
name = "pebble-sys"
version = "0.0.1"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
publish = false

autotests = false
autobenches = false
autoexamples = false

[lib]
name = "pebble_sys"
test = false
doctest = false
bench = false

[dependencies]
